#!/usr/bin/env bash

for hook in $(dirname "$0")/pre-commit.d/* ; do
    if [ -f $hook ]
    then
        bash $hook
        RESULT=$?
        if [ test $RESULT -ne 0 ]; then
            echo "$hook returned non-zero: $RESULT, abort commit"
            exit $RESULT
        fi
    fi
done
