#!/usr/bin/env bash

for hook in $(dirname "$0")/pre-commit.d/* ; do
    bash $hook
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done
